# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_conference', '0002_auto_20180120_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([]),
        ),
    ]
